### ISSUE TITLE
Export / Import error in the adapter

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.s7#10]
Beim exportieren von Daten aus dem Adapter werden Punkte (Byte.Bit) mitexportiert. Beimanschliessenden importieren wird jedoch zusätzlich noch ein Punkt eingefügt. Die Daten haben dann zwei Punkte (Byte..Bit). Siehe Forum --> http://forum.iobroker.net/viewtopic.php?f=36&t=7209&start=80#p115823
Der Fehler betrifft nur die Reiter Eingänge, Ausgänge und Merker, beim Reiter DBs funktioniert es. Dort werden vorhandene Punkte nicht mitexportiert.

**Comment by fu-zhou** [comment]
Dann kommt noch dazu, dass die Räume nicht mitimportiert werden, auch wenn man sie unter Aufzählungen - enum.rooms schon angelegt hat. Am einfachsten wäre es natürlich, wenn die Räume beim importieren automatisch unter enum.rooms angelegt werden. 

"Rolle" wird importiert, sollte dann aber auch um die Rollen erweitert werden, die noch nicht existieren, z.B. value.position. Importiert man einen Datenpunkt mit einer Rolle, die es noch nicht gibt, bleibt das Feld "Rolle" leer.

Wenn man Datenpunkte importiert, die es schon gibt, sollten diese überschrieben werden. Im Moment tauchen die Datenpunkt im S7 Adapter dann doppelt auf, z.B.:

20 | 0 | 0 | TASTER_A2_0 | HV_Eingangsbereich_Außenbeleuchtung_Licht_EIN | BOOL |   | 0-1 | switch | EG_Haustür | true | true | true

20 | 0 | 0 | TASTER_**A4_0** | HV_**Garage**_Außenbeleuchtung_Licht_EIN | BOOL |   | 0-1 | switch | EG_Haustür | true | true | true

D.h. bei Änderungen muss ich erst alles löschen (weil selektiv löschen nur Datenpunkt für Datenpunkt geht) und dann alles wieder importieren. Wenn ich z.B. Änderungen an 10 Datenpunkten habe, würde ich die gerne über CSV importieren und die alten Datenpunkte (identifizierbar über die Adresse) einfach überschreiben - was jetzt nicht geht, weil die Einträge im Moment dann doppelt sind.
