### ISSUE TITLE
Faktor für Objekte in der Akapterkonfiguration

### ISSUE THREAD

**Issue by JackBlack77** [ioBroker/ioBroker.s7#11]
Ist es möglich einen Faktor für die Objekte in der Adapterkonfiguration einzufügen (genauso wie es bereits im Modbus-Adapter bereits umgesetzt ist). Ich habe bis jetzt keine möglichkeit gefunden die gelesenen Werte (z.B. Klimadaten) zu skalieren.

**Comment by GermanBluefox** [comment]
You can use aliases, javascript or rules to multiply the data
