### ISSUE TITLE
Problem beim Ansprechen von Netzwerk-Eingängen Siemens Logo 8

### ISSUE THREAD

**Issue by Marten0815** [ioBroker/ioBroker.s7#12]
Hallo,
habe ein Problem mit dem ansprechen von Netzwerk Eingängen. Sobald ich die Adresse einfüge funktioniert das Adapter nicht mehr bzw. die Abfragen von VM Adressen nicht mehr. Habe den Fehlercode Angefügt:

host.raspberrypi | 2018-10-31 21:22:01.511 | error | instance system.adapter.s7.0 terminated with code 0 (OK)
-- | -- | -- | --
host.raspberrypi | 2018-10-31 21:22:01.510 | error | Caught by controller[0]: at Decoder.add (/home/pi/node_modules/socket.io-parser/index.js:246:12)
host.raspberrypi | 2018-10-31 21:22:01.510 | error | Caught by controller[0]: at Decoder.Emitter.emit (/home/pi/node_modules/component-emitter/index.js:134:20)
host.raspberrypi | 2018-10-31 21:22:01.509 | error | Caught by controller[0]: at Decoder.<anonymous> (/home/pi/node_modules/component-bind/index.js:21:15)
host.raspberrypi | 2018-10-31 21:22:01.509 | error | Caught by controller[0]: at Manager.ondecoded (/home/pi/node_modules/socket.io-client/lib/manager.js:332:8)
host.raspberrypi | 2018-10-31 21:22:01.508 | error | Caught by controller[0]: at Manager.Emitter.emit (/home/pi/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
host.raspberrypi | 2018-10-31 21:22:01.507 | error | Caught by controller[0]: at Manager.<anonymous> (/home/pi/node_modules/component-bind/index.js:21:15)
host.raspberrypi | 2018-10-31 21:22:01.506 | error | Caught by controller[0]: at Socket.onpacket (/home/pi/node_modules/socket.io-client/lib/socket.js:236:12)
host.raspberrypi | 2018-10-31 21:22:01.506 | error | Caught by controller[0]: at Socket.onack (/home/pi/node_modules/socket.io-client/lib/socket.js:312:9)
host.raspberrypi | 2018-10-31 21:22:01.505 | error | Caught by controller[0]: at Socket.<anonymous> (/home/pi/node_modules/iobroker.s7/main.js:159:21)
host.raspberrypi | 2018-10-31 21:22:01.505 | error | Caught by controller[0]: at prepareWrite (/home/pi/node_modules/iobroker.s7/main.js:175:20)
host.raspberrypi | 2018-10-31 21:22:01.503 | error | Caught by controller[0]: TypeError: Cannot read property 'native' of null
s7.0 | 2018-10-31 21:22:00.949 | error | TypeError: Cannot read property 'native' of null at prepareWrite (/home/pi/node_modules/iobroker.s7/main.js:175:20) at Socket.<anonymous> (/home/pi/node_modules/iobroker.s7/main.js:159:21)
s7.0 | 2018-10-31 21:22:00.947 | error | uncaught exception: Cannot read property 'native' of null

**Comment by Apollon77** [comment]
try 1.1.9
