### ISSUE TITLE
S7 Logo in der Instanzansicht wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.s7#137]
Hallo,

in der Instanzansicht wird das S7 Logo nicht mehr angezeigt.

![image](https://user-images.githubusercontent.com/35137293/179524010-74b0cadc-23bf-4cab-a6b2-636ff25f2c37.png)

da müsste normalerweise diese Logo angezeigt werden.

![image](https://user-images.githubusercontent.com/35137293/179524920-7602da6f-a9aa-4778-b93e-aa1b29ec3f75.png)

in der Dev-Konsole wird der folgende Fehler angezeigt:

`
GET http://192.168.0.55:8081/adapter/s7/S7.png 404 (Not Found)

Image (async)

Zs @ react-dom.production.min.js:262

Gs @ react-dom.production.min.js:260

Gs @ react-dom.production.min.js:260

Xc @ react-dom.production.min.js:259

bc @ react-dom.production.min.js:283

$n @ react-dom.production.min.js:281

bs @ react-dom.production.min.js:270

Ln @ scheduler.production.min.js:13

Gn @ scheduler.production.min.js:14
`

Das Logo hat den Dateinamen s7.png, im GET Befehl wird der Dateiname mit S7.png angegeben. Das "S" ist groß geschrieben, vielleicht ist das der Fehler?

Gruß Steffen

**Comment by Bettman66** [comment]
Das kannst du in der io-package.json ändern.
"icon": "S7.png", 
in 
"icon": "s7.png",

**Comment by Apollon77** [comment]
ja werde ich fixen

**Comment by Steff42** [comment]
Na Super,
jetzt habe ich hier einen commit erstellt, in dem die Änderung von @Bettman66 drin ist, aber ich kriege das mit dem PullRequest nicht gebacken.

**Comment by Steff42** [comment]
@GermanBluefox ,

Thx for merging. Works now as expected.
