### ISSUE TITLE
Export des DB´s nicht möglich, Scrollbalken

### ISSUE THREAD

**Issue by HansPeterMeier** [ioBroker/ioBroker.s7#17]
Guten Tag,
ich habe ein Problem mit dem S7 Adapter. Wenn sehr viele Datenpunkte angegeben sind, ist es nicht möglich bis nach unten zu Scrollen um den Export durchzuführen.
Die Funktion "In Zwischenablage" scheint auch nicht zu funktionieren, wäre mir da aber noch egal, wenn ich bis zum letzten Datensatz scrollen könnte.
Dieses tritt beim Chromium, Iexplorer, Firefox, Safari auf.
Adapter ist 1.1.4.

Gruß und Danke

![image](https://user-images.githubusercontent.com/32676715/59993397-72422b80-9650-11e9-87ec-995d37a07785.png)

**Comment by fu-zhou** [comment]
Muss ich leider auch feststellen: Leider funktioniert der CSV-Export der DBs im S7 Adapter nicht. Es kommt zwar die Meldung "Text wurde in die Zwischenablage kopiert", da ist dann aber nichts, was z.B. im Text-Editor eingefügt werden kann, um die Datenpunkte zu sichern. V1.1.7

**Comment by ambo11** [comment]
gleiches Problem - der Text wird nicht in die Zwischenablage kopiert und man kann ihn leider auch nicht auswählen. - V1.1.8
