### ISSUE TITLE
Connect the IOBroker with Siemens Logo - Documentation

### ISSUE THREAD

**Issue by mj2680** [ioBroker/ioBroker.s7#19]
I am new in the forum and I have the following issue:
The IO Broker works fine in my smart home project. Now I would like to add the S7 Logo (V7) to the IOBroker, but I have no change to connect both components. The S7 Logo adapter works fine (green LED) but I cannot send data from the IO Broker to the Logo. 
Perhaps somebody have a detail documentation for this connection ?

I try to find something in this forum, but the documention is only available for the S7-300 with DBs.

Thanks for your help

**Comment by Apollon77** [comment]
How you tried it? Normally just use Admin and set values. Else please show what you tried
