### ISSUE TITLE
S7 1200 connection problem

### ISSUE THREAD

**Issue by BKaresz** [ioBroker/ioBroker.s7#22]
Hello.
I just find a mistake in the code (main.js)
        main.acp.rack  = parseInt(main.acp.rack,  10)  || 0;
        **main.acp.slot   = parseInt(main.acp.slot,  10)  || 2;**
In case of S7-1200 PLC you have to use rack and slot number 0 but it is not possible to set up in the current version, so I modified and it is working now.
        main.acp.rack  = parseInt(main.acp.rack,  10)  || 0;
        **main.acp.slot   = parseInt(main.acp.slot,  10)  || 0;**
BR.

**Comment by Apollon77** [comment]
A line number would have also helped ;-) I fixed it differently ...

**Comment by BKaresz** [comment]
> A line number would have also helped ;-) I fixed it differently ...

Hello.
Line 545.
How you fixed?
Bye.

**Comment by Apollon77** [comment]
fixed by https://github.com/ioBroker/ioBroker.s7/commit/e1b5daceae98aa3ec0031540b9517c5ccf16c3f5

Please try 1.1.7 from GitHub and give Feedback

**Comment by Apollon77** [comment]
Any success??

**Comment by BKaresz** [comment]
Sorry I didn't try your solution yet, may be in the weekend. Thanks.

**Comment by BKaresz** [comment]
Hi.
Sorry for late feedback, but I have no time..
I tried and it is working.
Thx.
