### ISSUE TITLE
Device connection status in adapter objects

### ISSUE THREAD

**Issue by MartiMan79** [ioBroker/ioBroker.s7#244]
Hi,

I'm using a script using array enums to update values between S7 and hmip.
I would like to stop my scripts when the PLC is not connected but this is not available in the objects list of the adapter. 
Only alive and connected but not connected to device.

Or am I missing something?

Thanks!

**Comment by MartiMan79** [comment]
@Apollon77 No there is only the alive and connection state of the adapter, not the device.
If the device is offline, both are still true.

![IMG_3009](https://github.com/ioBroker/ioBroker.s7/assets/56831581/ebfdd425-7382-4c22-b52f-1279b8721dda)

**Comment by Apollon77** [comment]
Please exactly look the object patch I posted !! you look in system.adapter.s7.0 which is a different path!!
