### ISSUE TITLE
Not work under Node.js v12.16.2

### ISSUE THREAD

**Issue by CNC-Maniac** [ioBroker/ioBroker.s7#27]
After I updated Node.js to 12.16.2, the adapter isn't working anymore. Any ideas how to fix this? I realy need this adapter again, otherwise I hav to go back to 10.x.x.

**Comment by Apollon77** [comment]
Any error log available?

**Comment by CNC-Maniac** [comment]
Sorry, I removed the adapter already and reinstalled it again. Now is seem to be okay.
