### ISSUE TITLE
Nach Update auf JSC 3.0.20 Warnmeldungen im LOG

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.s7#28]
Hallo,
seit dem Update auf den JSC 3.0.20 bekomme ich folgende Warnmeldung(en) im LOG
![image](https://user-images.githubusercontent.com/35137293/80568567-8cc6fd00-89f7-11ea-99b4-70c9e3259432.png)
Gruß Steffen

**Comment by Steff42** [comment]
Habe mir mal das JSON eines der Objekte, das angewarnt wird angeschaut.
![image](https://user-images.githubusercontent.com/35137293/80592321-8ba9c600-8a1f-11ea-94da-845d9671ebdc.png)
Das Problem kommt daher, das dort eine Zahl steht.
Gruß Steffen

**Comment by Apollon77** [comment]
Jupp da empfehlt ein .toString()

**Comment by Steff42** [comment]
Gerade gesucht, gefunden und getestet!
S7-Adapter gestoppt.
In der main.js jeweils in den Zeilen 771 (Inputs), 809 (Outputs) und 847 (Markers) ein .toString() angehängt.
S7-Adapter gestartet und die Warnungen sind weg.

**Comment by Apollon77** [comment]
Kannst du einen PR machen dazu? Ansonsten reichen diese super Infos for mich die Tage auch. Danke

**Comment by Steff42** [comment]
Einen PR habe ich noch nie gemacht.
Habe mich mit den vielen Funktionen im Github noch nicht wirklich auseinandergesetzt bzw. auch nicht verstanden wie das genau funktioniert und welche Voraussetzungen ich dazu benötige.
Sorry!

**Comment by Steff42** [comment]
@Apollon77,
habe mich mal an einem PR versucht.
Hoffe das passt so!
Gruß Steffen
