### ISSUE TITLE
S7 Adapter negative Werte 

### ISSUE THREAD

**Issue by Tuning1** [ioBroker/ioBroker.s7#301]
Ich habe schon einige Zeit den Iobroker in Betrieb.
Ich habe immer wieder das Problem, wenn ich den Datenpunkt von einer Siemens Logo 8 einlese,
wird der Wert 65511 angezeigt. Alle anderen Werte die genau so eingelesen werden, von der Logo, sind richtig.
Jetzt dürfte ich einmal den Fehler eingegrenzt haben, es dürfte sein wenn der Wert negativ ist.
Der Datenpunkt ist als Word definiert so wie alle anderen auch.
Kann der S7 Adapter keine negativen Werte von der Logo einlesen?

**Comment by Apollon77** [comment]
potentially duplicate #13? Try 1.4.3 coming soon
