### ISSUE TITLE
V1.1.10: S7 Adapter bleibt "gelb" kommuniziert aber mit der S7

### ISSUE THREAD

**Issue by fu-zhou** [ioBroker/ioBroker.s7#37]
@smiling-Jack : schön, wieder was von dir zu hören! Ich habe heute gleich den Adapter aktualisiert, mit dem Ergebnis aus dem Titel. Was kann ich tun? (Unterstützung beim Debuggen etc.)
![Zwischenablage06](https://user-images.githubusercontent.com/11984960/105681814-ed855680-5ef1-11eb-9329-5d04670ff055.jpg)

Kümmerst du dich auch um z.B. https://github.com/ioBroker/ioBroker.s7/issues/17 ?

Gruß!

**Comment by ChrisM246** [comment]
Habe leider das gleiche Problem, die Verbindung scheint aber trotzdem zu funktionieren. Ein Einfacher Anzeigefehler vielleicht?

**Comment by Bettman66** [comment]
Ich schließe mich an.

**Comment by Apollon77** [comment]
Bitte GitHub version (bzw morgen latest 1.2.1) versuchen

**Comment by fu-zhou** [comment]
1.2.2 funktioniert wieder!
