### ISSUE TITLE
S7 Instanz läuft nur mit einer String länge von 2 und diese ist nicht veränderbar 

### ISSUE THREAD

**Issue by KSJakobsen** [ioBroker/ioBroker.s7#71]
**Describe the bug**  
Beim Anlegen von Strings in der S7 Instanz ist eine Länge von 2 vorgegeben und ausgegraut. Hiermit läuft die Instanz. Über den Import einer TSV kann man diesen Wert vergrößern, dann funktioniert die Instanz aber nicht mehr

**To Reproduce**  
1. Öffne Instanz - Einstellungen des S7 Adapters
2. Gehe zu DB
3. Füge eine Zeile hinzu
4. Wähle als Typ String aus -> Länge 2 ist vorgegeben und ausgegraut und somit nicht editierbar
5. Bearbeite TSV
6. Ändere Länge der Strings auf einen Wert != 2
7. Importiere die TSV
8. Speichern und schließe
9. Siehe da Die Instanz startet nicht mehr

**Expected behavior**  
Eine beliebige Länge des Strings eintragen zu können und der Adapter noch funktioniert

**Screenshots & Logfiles**  
![Screenshot from 2021-08-26 16-52-35](https://user-images.githubusercontent.com/44235327/130986322-9cbb5adc-4e60-445a-a2ed-72f50d3305fc.png)
![Screenshot from 2021-08-26 16-51-37](https://user-images.githubusercontent.com/44235327/130986332-2de8c232-dc31-4f4c-aa51-b4b308f9e54f.png)
![Screenshot from 2021-08-26 16-52-05](https://user-images.githubusercontent.com/44235327/130986335-780db39e-cb47-4928-bd64-a29a6930d520.png)
![Screenshot from 2021-08-26 16-50-47](https://user-images.githubusercontent.com/44235327/130986337-343c06f2-c521-4ffc-9bf1-4a06c1657469.png)

**Versions:**  
 - Adapter version: 1.3.6
 - JS-Controller version: 3.3.15
 - Node version: 14.17.1
 - Operating system: Debian 10

**Additional context**

**Comment by Zerotwo3185** [comment]
Ja kann ich bestätigen habe das gleiche Problem. Habe jetzt ein altes Backup aufgespielt um dann Adapter in der Version 1.2.5 zu verwenden. Jetzt läuft alles wieder stabil.

**Comment by Apollon77** [comment]
Ändern der Länge geht im Expertenmodus in Admin5. Bitte Aktivieren. Das "size" isue (siehe auch #87) will be fixed soon

**Comment by Apollon77** [comment]
Bitte GitHub version versuchen, nach Installation Adapter restarten.

**Comment by GermanBluefox** [comment]
please test v1.3.9
