### ISSUE TITLE
S7 Adapter empfängt falsche Datentypen 

### ISSUE THREAD

**Issue by Stefan592** [ioBroker/ioBroker.s7#76]
Es wird eine Warnmeldung ausgeben das die falschen Datentypen empfangen werden. Siehe Screenshots.
Wert stimmt auch nicht überein. Variable 'gateGardenIsClosed' sollte im ioBroker TRUE sein.

Parametrierung ist meiner Meinung nach korrekt.

PLC:
![image](https://user-images.githubusercontent.com/14180760/132812100-ebdb8a19-d111-4f31-b490-196efccc4177.png)

Objects:
![image](https://user-images.githubusercontent.com/14180760/132812138-05f9a462-cc90-4fa9-ac8b-3a96e5b16a98.png)

Instance config:
![image](https://user-images.githubusercontent.com/14180760/132812172-7770c01d-7378-46b7-9630-f4ce462951cd.png)

Log:
![image](https://user-images.githubusercontent.com/14180760/132812206-b2dc7ceb-6c59-4a46-b449-8f68a9769578.png)

**Comment by Apollon77** [comment]
Bitte betroffene Objekte mal löschen und adapter restarten. Meldungen danach weg?

**Comment by Stefan592** [comment]
> Bitte betroffene Objekte mal löschen und adapter restarten. Meldungen danach weg?

Nein. Die Datenpunkte werden wieder neu angelegt und die Meldung erscheint wieder.

**Comment by Apollon77** [comment]
Dann itte Logging mal Debug stellen und schauen ob mehr Log messages kommen

**Comment by Stefan592** [comment]
Leider kommt selbst auf Log Stufe "Debug" oder "Alles" nicht viel mehr raus:

<html>
<body>


s7.0 | 2021-09-10 09:32:26.592 | info | Successfully connected in S7 mode
-- | -- | -- | --
s7.0 | 2021-09-10 09:32:26.583 | info | Connect in S7 mode to 0 / 1
s7.0 | 2021-09-10 09:32:26.484 | warn | This object will not be created in future versions. Please report this to the developer.
s7.0 | 2021-09-10 09:32:26.483 | warn | Object DBs.DB1.gateGardenIsClosed is invalid: obj.common.write has an invalid type! Expected "boolean", received "string"
s7.0 | 2021-09-10 09:32:26.437 | warn | This object will not be created in future versions. Please report this to the developer.
s7.0 | 2021-09-10 09:32:26.436 | warn | Object DBs.DB1.gateKatjaIsClosed is invalid: obj.common.write has an invalid type! Expected "boolean", received "string"
s7.0 | 2021-09-10 09:32:26.163 | info | starting. Version 1.3.6 in /opt/iobroker/node_modules/iobroker.s7, node: v12.22.5, js-controller: 3.2.16
s7.0 | 2021-09-10 09:32:25.658 | debug | Plugin sentry Initialize Plugin (enabled=true)


</body>
</html>

**Comment by Stephan84** [comment]
Ich habe die gleichen Meldungen:

s7.0 | 2021-10-20 23:04:05.898 | info | Successfully connected in LOGO! mode
s7.0 | 2021-10-20 23:04:05.887 | info | Connect in LOGO! mode to 512 / 256
s7.0 | 2021-10-20 23:04:05.806 | warn | This object will not be created in future versions. Please report this to the developer.
s7.0 | 2021-10-20 23:04:05.805 | warn | Object s7.0.DBs.DB1.Q4 is invalid: obj.common.write has an invalid type! Expected "boolean", received  "string"
s7.0 | 2021-10-20 23:04:05.712 | info | starting. Version 1.3.6 in /opt/iobroker/node_modules/iobroker.s7, node: v12.22.7, js-controller: 3.3.18

Bei mir werden die Werte in ioBroker aber passend angezeigt (wenn der Logo Ausgang 1 ist, zeigt ioBroker true an).

**Comment by Apollon77** [comment]
Ok I assume the new UI is responsible.Can yu please show the native part of "system.adapter.s7.0" object? I need to see whats in the values. Ideallay have some with "RW" and some without please. Or Poll yes/no

@GermanBluefox it seems that the UI wrotes booleans as strings in config ... also "Length" is written as String which casued another issue ... I will have a commit for that soon

**Comment by GermanBluefox** [comment]
Please test v1.3.7

**Comment by Apollon77** [comment]
1.3.7. will not fix anything ... only the "write no boolean" issue ... I have some more fixes soon

**Comment by Apollon77** [comment]
Bitte GitHub version versuchen, nach Installation Adapter restarten.
