### ISSUE TITLE
DB Import nicht möglich

### ISSUE THREAD

**Issue by ryto1** [ioBroker/ioBroker.s7#81]
Beim Versuch eine .csv Datei mit den Daten meines DBs in den Adapter zu importieren kommt nur kurz die Meldung "data updated".
Es wird nichts importiert, Fehlermeldung erscheint keine.

Alle Adapter sind aktuell (Beta)
Node 12.16.2
NPM 6.14

**Comment by GermanBluefox** [comment]
Kannst du csv geben?

**Comment by ryto1** [comment]
Anbei die 2 dateien.Danke
-------- Ursprüngliche Nachricht --------Von: Bluefox ***@***.***> Datum: 09.11.21  12:33  (GMT+01:00) An: "ioBroker/ioBroker.s7" ***@***.***> Cc: ryto1 ***@***.***>, Author ***@***.***> Betreff: Re: [ioBroker/ioBroker.s7] DB Import nicht möglich
  (#81) 
Kannst du csv geben?

**Comment by Apollon77** [comment]
You need to attach them in web please. Attaching files do not work via email replies

**Comment by smolo-de** [comment]
[import_db17_iob.csv](https://github.com/ioBroker/ioBroker.s7/files/7510909/import_db17_iob.csv)
[import_db17_iob.txt](https://github.com/ioBroker/ioBroker.s7/files/7510935/import_db17_iob.txt)

**Comment by ryto1** [comment]
[db12.csv](https://github.com/ioBroker/ioBroker.s7/files/7519727/db12.csv)

**Comment by schneewa** [comment]
ich müsste einen String oder einen S7String auf die Länge von 254 setzen - leider ist auch im Expertrenmodus die Länge  deaktiviert - ist nicht veränderbar

Auch schaffe ich es leider nicht eine .tsv bzw. eine .csv zu importieren - leider funktionieren auch die Vorlagen von smolo-de  nicht.

Admin - V5.5.3
S7 Adapter - V1.3.10 
Host - V3.3.22

hat von den Experten einer eine Idee

vielen Dank
