### ISSUE TITLE
String from IoB to S7 does not work

### ISSUE THREAD

**Issue by smolo-de** [ioBroker/ioBroker.s7#87]
Transfer of string from IoB to S7 does not work with following error:

s7.0 | 2021-11-07 12:18:08.504 | error | (19312) Exception-Code: ERR_INVALID_ARG_TYPE: The "size" argument must be of type number. Received type string ('202')
s7.0 | 2021-11-07 12:18:08.503 | error | (19312) TypeError [ERR_INVALID_ARG_TYPE]: The "size" argument must be of type number. Received type string ('202')     at Function.alloc (buffer.js:370:3)     at send (/opt/iobroker/node_modules/iobro
s7.0 | 2021-11-07 12:18:08.502 | error | (19312) uncaught exception: The "size" argument must be of type number. Received type string ('202')

S7 1500 with db element with STRING[20]

I think the error can be located at this line https://github.com/ioBroker/ioBroker.s7/blob/ce5e84ba5f18d6b83a4172f32b935ec34bcc0077/main.js#L319 because there could be an api change in nodejs. There was a known error in PLCHome NodeRed Adapter.

https://github.com/PLCHome/node-red-contrib-ads/issues/19#issuecomment-487273600

old: var stringbuf = new Buffer(val.toString().slice(0,convert.length-1) + '\0', 'binary')
wrong: var stringbuf = Buffer.alloc(val.toString().slice(0,convert.length-1) + '\0', 'binary')
new: var stringbuf = Buffer.from(val.toString().slice(0,convert.length-1) + '\0', 'binary')

**Comment by Apollon77** [comment]
And how the config looks for this? We could make sure ".len" is a number

**Comment by smolo-de** [comment]
> 
> 
> And how the config looks for this? We could make sure ".len" is a number

PLC:
![grafik](https://user-images.githubusercontent.com/9969181/140651958-51831c7f-87e0-4f6f-8a3e-8bafd507ec0b.png)

S7 Adapter:
![grafik](https://user-images.githubusercontent.com/9969181/140652019-5cf39d02-653b-44d9-bfcd-8aa86cafa633.png)

Object:
![grafik](https://user-images.githubusercontent.com/9969181/140652092-cb41180f-8f13-45ba-a531-ca11e6b4ddb2.png)

The bug with length of 2 is known.

**Comment by Apollon77** [comment]
Ja das "len" hab ich beu mir denke schin gefickt. kann ich später pushen ... das mit "rw und poll"bezüg sich auf das andere issue ...

**Comment by Apollon77** [comment]
Bitte GitHub version versuchen, nach Installation Adapter restarten.

**Comment by GermanBluefox** [comment]
Please test v1.3.9

**Comment by smolo-de** [comment]
Perfect no more problems 👍 

Tested with S7 1515-2pn
