### ISSUE TITLE
S5Time from IoB to S7 does not work 

### ISSUE THREAD

**Issue by smolo-de** [ioBroker/ioBroker.s7#88]
Transfer of s5time from IoB to S7 does not work and no error messages. The error has existed for a longer time.
Reading is no problem and works perfect.

PLC
![image](https://user-images.githubusercontent.com/9969181/140998447-97fa1183-3e04-40d6-a953-1565f45d9765.png)

Adapter
![image](https://user-images.githubusercontent.com/9969181/140998555-4fe0df01-6c42-4612-919c-93ac2b2e2b2c.png)

Object
![image](https://user-images.githubusercontent.com/9969181/140998698-f5624d76-bf70-4c30-ab1b-6c90f212e62c.png)

Read from DB
![image](https://user-images.githubusercontent.com/9969181/140999278-e8001b7b-e1d2-481e-94ea-1e8952740bde.png)

if i change the value from 3600 to 1800 nothing happens to s7 but the adapter sets the value to 360?!
![image](https://user-images.githubusercontent.com/9969181/140999510-d314cf87-3283-4f62-b805-385591040748.png)

Logfile with Silly Mode
![image](https://user-images.githubusercontent.com/9969181/140999726-800b1ed6-8250-46bf-b88b-6591dc66e590.png)

**Versions:**  
 - S7 Adapter with Release v1.3.9
 - JS-Controller version: 3.3.18
 - Node version: v12.22.7
 - Operating system: Docker
-  PLC: S7 1500 (1515)

**Comment by Apollon77** [comment]
I find in code logic to read the S5TIME valiue, but I do not see code to write such a value... @GermanBluefox ?
