### ISSUE TITLE
possibility to set connection type (PG/OP/Other)

### ISSUE THREAD

**Issue by boeskij** [ioBroker/ioBroker.s7#92]
It would be nice if it was possible to set the connection type as described here:
http://snap7.sourceforge.net/plc_connection.html

> By default the client connects as a PG (the programming console), with this function is possible change the connection resource type to OP (the Siemens HMI panel) or S7 Basic (a generic data transfer connection).

If connected as a PG in some circumstances it is noch possible to connect to the CP anymore via programming console because of limited connection resources.

**Comment by jogibear9988** [comment]
I think

If we would call "SetConnectionType" before this line
https://github.com/ioBroker/ioBroker.s7/blob/master/main.js#L1087
it would work

Here is a description of the possible types:
https://github.com/dotnetprojects/DotNetSiemensPLCToolBoxLibrary/blob/master/LibNoDaveConnectionLibrary/Communication/PLCConnectionConfiguration.cs#L977
